name: Tag JAR on Push to Main

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build-and-tag:
    runs-on: ubuntu-latest  # You can change this to other OS types if needed

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK (if you're using Gradle/Maven for building)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust version if needed
          distribution: 'temurin'

      # Step 3: Build your JAR (this example assumes you're using Gradle)
      - name: Build JAR
        run: cd proto-java && ./gradlew build

      # Step 4: Create Git tag based on the current timestamp or use any other naming convention
      - name: Create Git tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')" 
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME
          ls proto-java/build
          ls proto-java/build/libs

      # Step 5: Create a GitHub Release
      - name: Create GitHub Release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: ${{env.TAG_NAME}}
          release_name: "Release ${{env.TAG_NAME}}"
          body: "Automatically generated release for ${{env.TAG_NAME}}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  # Token for authentication

      # Step 6: Upload the JAR as a release asset
      - name: Upload JAR as a Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}  # URL from create-release step
          asset_path: ./proto-java/build/libs/*.jar  # Path to your JAR file
          asset_name: approval-library-${{env.TAG_NAME}}.jar  # Name of the file in the release
          asset_content_type: application/java-archive  # MIME type for JAR files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication